using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using System;
using UnityEngine.SceneManagement;
public class CreateDate : MonoBehaviour
{
    //ï¿½ï¿½ï¿½tï¿½æ“¾ï¿½p
    public static DateTime SelectDate;
    private DateTime D_Date;
    private int startday;
    public static DateTime ToDate;
    //ï¿½wï¿½è‚µï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½çµï¿½ï¿½ï¿½Ô‚ï¿½\ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Öï¿½
    private void CalenderController(DateTime headdate)
    {   D_Date = headdate;
        Debug.Log(D_Date);
        for (int i = 0; i < 7; i++)
        {
            if (i == 0)
            {
                Title.GetComponent<SetTitle>().TitleController(headdate);
            }
            //ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
            Transform DAY = GameObject.Find("Dates").transform.GetChild(i);
            DateTime tmp = D_Date;//ï¿½êŸï¿½Ïï¿½
            DayOfWeek num = tmp.DayOfWeek;
            //ï¿½yï¿½jï¿½ï¿½ï¿½ÂEï¿½ï¿½ï¿½jï¿½ï¿½ï¿½ï¿½
            switch (num)
            {
                case DayOfWeek.Sunday:
                    DAY.GetChild(0).GetChild(0).GetComponent<Text>().color = Color.red;
                    break;
                case DayOfWeek.Saturday:
                    DAY.GetChild(0).GetChild(0).GetComponent<Text>().color = Color.blue;
                    break;
                default:
                    DAY.GetChild(0).GetChild(0).GetComponent<Text>().color = Color.black;
                    break;

            }
            DAY.GetChild(0).GetChild(0).GetComponent<Text>().text = D_Date.ToString("MM/dd");
            DAY.GetChild(0).GetChild(1).GetComponent<Text>().text = D_Date.ToString("(ddd)");
            GameObject button = GameObject.Find("Dates").transform.GetChild(i).GetChild(0).gameObject;
            //ï¿½{ï¿½^ï¿½ï¿½ï¿½É‚ï¿½ï¿½Ì“ï¿½ï¿½tï¿½ï¿½Û‘ï¿½
            button.transform.parent.GetComponent<ButtonDate>().day = D_Date;
            DateTime d = D_Date;
            button.GetComponent<Button>().onClick.AddListener(() => { ToDetailScene(d); });
            D_Date = D_Date.AddDays(1);
        }
        SetPlanName();
    }
    //ï¿½ï¿½ï¿½Xï¿½gï¿½É•Ûï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½\ï¿½ï¿½ï¿½ï¿½Yï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½tï¿½É•\ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½.
    public void SetPlanName()
    {
        int i;
        Debug.Log("datacount:" + PlanList.datacount);
        //7ï¿½ï¿½ï¿½Ô‚Ì—\ï¿½è‰ï¿½ï¿½ï¿½ï¿½(ï¿½vï¿½ï¿½ï¿½nï¿½uï¿½íœ)
        for(i=0; i<7; i++)
        {
            GameObject parent = this.transform.GetChild(i).GetChild(0).GetChild(2).gameObject;
            foreach (Transform child in parent.transform)
            {
                GameObject.Destroy(child.gameObject);
            }
        }

        for (i=0; i<PlanList.datacount; i++)
        {
            //Debug.Log(i);
            //Debug.Log("Sel:"+SelectDate);
            //Debug.Log("S:" + PlanList.DataList[i].Start);
            //Debug.Log("F:" + PlanList.DataList[i].Finish);
            if (PlanList.DataList[i].Finish <= SelectDate.Date || SelectDate.AddDays(7).Date <= PlanList.DataList[i].Start)
            {//ï¿½\ï¿½è‚ªï¿½\ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½7ï¿½ï¿½ï¿½Ô‚ÌŠÔ‚É‚È‚ï¿½ï¿½ï¿½
                Debug.Log("Case1");
                continue;
            }else if (PlanList.DataList[i].Start <= SelectDate.Date)
            {//ï¿½\ï¿½ï¿½Jï¿½nï¿½ï¿½ï¿½ï¿½ï¿½æ“ªï¿½Ì“ï¿½ï¿½tï¿½ï¿½00:00ï¿½ï¿½ï¿½ï¿½ï¿½O
                if(PlanList.DataList[i].Finish <= SelectDate.AddDays(7).Date)
                {//ï¿½\ï¿½ï¿½Iï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ÅŒï¿½ï¿½ï¿½Ì“ï¿½ï¿½t+1ï¿½ï¿½00:00ï¿½È‘O
                    Debug.Log("Case2");
                    int j = 0;
                    do
                    {
                        GameObject planview = this.transform.GetChild(j).GetChild(0).GetChild(2).gameObject;
                        //ï¿½\ï¿½ï¿½Ìƒ{ï¿½^ï¿½ï¿½ï¿½ì¬
                        GameObject planpanelobj = Instantiate(planpanel, planview.transform);
                        Debug.Log(planpanelobj.name);
                        //ï¿½\ï¿½ï¿½Ì–ï¿½ï¿½O,ï¿½ï¿½ï¿½Ô‚ï¿½ï¿½Lï¿½ï¿½
                        planpanelobj.transform.GetChild(0).GetComponent<Text>().text = PlanList.DataList[i].Name;

                        if (SelectDate.Date.AddDays(j) == PlanList.DataList[i].Finish.Date)
                        {
                            planpanelobj.transform.GetChild(1).GetComponent<Text>().text = "ï¿½`" + PlanList.DataList[i].Finish.ToString("HH:mm");
                            Debug.Log("written");
                        }

                        j++;
                    } while ( SelectDate.Date.AddDays(j) < PlanList.DataList[i].Finish);
                }
                else
                {//ï¿½\ï¿½ï¿½Iï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ÅŒï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
                    Debug.Log("Case4");
                    int j ;
                    for(j=0 ; j < 7 ; j++)
                    {
                        GameObject planview = this.transform.GetChild(j).GetChild(0).GetChild(2).gameObject;
                        GameObject planpanelobj = Instantiate(planpanel, planview.transform);
                        planpanelobj.transform.GetChild(0).GetComponent<Text>().text = PlanList.DataList[i].Name;
                    }
                }
            }
            else
            {//ï¿½\ï¿½ï¿½Jï¿½nï¿½ï¿½ï¿½ï¿½ï¿½æ“ªï¿½Ì“ï¿½ï¿½tï¿½ï¿½00:00ï¿½È~
                if (PlanList.DataList[i].Finish <= SelectDate.AddDays(7).Date)
                {//ï¿½\ï¿½ï¿½Iï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ÅŒï¿½ï¿½ï¿½Ì“ï¿½ï¿½tï¿½È‘O
                    Debug.Log("Case5");
                    int j = 0;
                    //ï¿½\ï¿½ï¿½Jï¿½nï¿½ï¿½ï¿½ï¿½ï¿½æ“ªï¿½Ì“ï¿½ï¿½tï¿½ï¿½ï¿½ç‰½ï¿½Ô–Ú‚ï¿½
                    while(SelectDate.Date.AddDays(j) != PlanList.DataList[i].Start.Date)
                    {
                        j++;
                    }

                    do
                    {
                        GameObject planview = this.transform.GetChild(j).GetChild(0).GetChild(2).gameObject;
                        GameObject planpanelobj = Instantiate(planpanel, planview.transform);
                        planpanelobj.transform.GetChild(0).GetComponent<Text>().text = PlanList.DataList[i].Name;
                        if (SelectDate.Date.AddDays(j) == PlanList.DataList[i].Start.Date)
                        {
                            planpanelobj.transform.GetChild(1).GetComponent<Text>().text =PlanList.DataList[i].Start.ToString("HH:mm")+"ï¿½`";
                        }
                        if(SelectDate.Date.AddDays(j) == PlanList.DataList[i].Finish.Date)
                        {
                            planpanelobj.transform.GetChild(1).GetComponent<Text>().text += PlanList.DataList[i].Finish.ToString("HH:mm");
                        }
                        j++;
                    } while (SelectDate.Date.AddDays(j) < PlanList.DataList[i].Finish);
                }
                else
                {//ï¿½\ï¿½ï¿½Iï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ÅŒï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
                    Debug.Log("Case3");
                    int j = 0;
                    //ï¿½\ï¿½ï¿½Jï¿½nï¿½ï¿½ï¿½ï¿½ï¿½æ“ªï¿½Ì“ï¿½ï¿½tï¿½ï¿½ï¿½ç‰½ï¿½Ô–Ú‚ï¿½
                    while (SelectDate.Date.AddDays(j) != PlanList.DataList[i].Start.Date)
                    {
                        j++;
                    }

                    do
                    {
                        GameObject planview = this.transform.GetChild(j).GetChild(0).GetChild(2).gameObject;
                        GameObject planpanelobj = Instantiate(planpanel, planview.transform);
                        planpanelobj.transform.GetChild(0).GetComponent<Text>().text = PlanList.DataList[i].Name;
                        if (SelectDate.Date.AddDays(j) == PlanList.DataList[i].Start.Date)
                        {
                            planpanelobj.transform.GetChild(1).GetComponent<Text>().text = PlanList.DataList[i].Start.ToString("HH:mm") + "ï¿½`";
                        }
                        j++;
                    } while (j<7);
                }
            }
        }
    }

    //WeekChange.csï¿½ÅŒÄ‚Ñoï¿½ï¿½ï¿½ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½_ï¿½[ï¿½ğ—ˆTï¿½Éiï¿½ß‚ï¿½
    public void ToNextWeekCalender()
    {
        SelectDate = SelectDate.AddDays(7);
        CalenderController(SelectDate);    
    }
    
    //WeekChange.csï¿½ÅŒÄ‚Ñoï¿½ï¿½ï¿½ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½_ï¿½[ï¿½ï¿½ï¿½Tï¿½Éiï¿½ß‚ï¿½
    public void ToLastWeekCalender()
    {
        SelectDate = SelectDate.AddDays(-7);
        CalenderController(SelectDate);
    }
    public GameObject planpanel;
    public GameObject canvas;
    public GameObject prefab;
    public GameObject Title;
    RectTransform DatesPos;
    Vector2 DatesPosoff;
    // Start is called before the first frame update
    //ï¿½\ï¿½ï¿½fï¿½[ï¿½^ï¿½ï¿½ï¿½Ä‚Ñoï¿½ï¿½ï¿½ê‚½ï¿½ï¿½Éï¿½ï¿½sï¿½ï¿½ï¿½ï¿½ï¿½Kï¿½vï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    void Start()
    {
        
        //ï¿½{ï¿½^ï¿½ï¿½7ï¿½Âï¿½ï¿½ï¿½
        for (int i = 0; i < 7; i++)
        {
            GameObject button = Instantiate(prefab, canvas.transform);
            button.GetComponent<Button>();
        }
        //ï¿½Xï¿½Nï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ï¿½Ê‚Ìï¿½ï¿½ï¿½ï¿½lï¿½ï¿½ï¿½Lï¿½^
        DatesPos = this.GetComponent<RectTransform>();
        DatesPosoff = DatesPos.anchoredPosition;
        //ï¿½Åï¿½ï¿½Íï¿½ï¿½ï¿½ï¿½ï¿½ï¿½î€ï¿½É“ï¿½ï¿½tï¿½ï¿½ï¿½ì¬
        SelectDate = DateTime.Now;
        CalenderController(SelectDate);
    }

    void Update()
    {   //ï¿½ï¿½ÉƒXï¿½Nï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½tï¿½ï¿½Oï¿½Éiï¿½ß‚ï¿½
        if (DatesPos.anchoredPosition.y> 250)
        {
            this.GetComponent<RectTransform>().anchoredPosition=DatesPosoff;
            SelectDate=SelectDate.AddDays(1);
            CalenderController(SelectDate);
        }
        //ï¿½ï¿½ï¿½ÉƒXï¿½Nï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½tï¿½ï¿½ß‚ï¿½
        if (DatesPos.anchoredPosition.y < -250)
        {
            this.GetComponent<RectTransform>().anchoredPosition = DatesPosoff;
            SelectDate = SelectDate.AddDays(-1);
            CalenderController(SelectDate);
        }
    }
    //ï¿½\ï¿½ï¿½Ú×ƒVï¿½[ï¿½ï¿½ï¿½Ö‘Jï¿½ï¿½
    public void ToDetailScene(DateTime date)
    {
        ToDate = date;
        SceneManager.LoadScene("detail");
    }
}
